version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: restaurante_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: restaurante_db
      MYSQL_USER: restaurante_user
      MYSQL_PASSWORD: restaurante_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - restaurante_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: restaurante_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=restaurante_user
      - DB_PASSWORD=restaurante_password
      - DB_NAME=restaurante_db
    depends_on:
      database:
        condition: service_healthy
    networks:
      - restaurante_network
    volumes:
      - ./frontend/dist:/root/dist

volumes:
  mysql_data:

networks:
  restaurante_network:
    driver: bridge
